/** Catálogo inicial EnQuéGasto — precios referenciales CLP (Chile) */
export type PlatformSeed = {
  name: string;
  slug: string;
  category: string;
  logoUrl?: string | null;
  websiteUrl?: string | null;
  description?: string | null;
  priceMonthly?: number | null;
  priceYearly?: number | null;
  priceFamily?: number | null;
};

export const PLATFORMS: PlatformSeed[] = [
  // Streaming
  { name: 'Netflix', slug: 'netflix', category: 'Streaming', websiteUrl: 'https://www.netflix.com', description: 'Series y películas', priceMonthly: 7990, priceYearly: null, priceFamily: 12990 },
  { name: 'Disney+', slug: 'disney-plus', category: 'Streaming', websiteUrl: 'https://www.disneyplus.com', description: 'Disney, Marvel, Star Wars', priceMonthly: 6990, priceFamily: 10990 },
  { name: 'Max', slug: 'max', category: 'Streaming', websiteUrl: 'https://www.max.com', description: 'HBO y Warner', priceMonthly: 7990, priceFamily: 11990 },
  { name: 'Amazon Prime Video', slug: 'prime-video', category: 'Streaming', websiteUrl: 'https://www.primevideo.com', description: 'Prime Video + beneficios Amazon', priceMonthly: 4990 },
  { name: 'Spotify', slug: 'spotify', category: 'Música', websiteUrl: 'https://www.spotify.com', description: 'Música y podcasts', priceMonthly: 4990, priceFamily: 7990 },
  { name: 'Apple Music', slug: 'apple-music', category: 'Música', websiteUrl: 'https://music.apple.com', description: 'Catálogo Apple', priceMonthly: 4990, priceFamily: 7990 },
  { name: 'YouTube Premium', slug: 'youtube-premium', category: 'Streaming', websiteUrl: 'https://www.youtube.com/premium', description: 'Sin anuncios + YouTube Music', priceMonthly: 7990, priceFamily: 12990 },
  { name: 'YouTube Music', slug: 'youtube-music', category: 'Música', websiteUrl: 'https://music.youtube.com', description: 'Música de YouTube', priceMonthly: 4990 },
  { name: 'Paramount+', slug: 'paramount-plus', category: 'Streaming', websiteUrl: 'https://www.paramountplus.com', description: 'CBS y Paramount', priceMonthly: 5990 },
  { name: 'Star+', slug: 'star-plus', category: 'Streaming', websiteUrl: 'https://www.starplus.com', description: 'ESPN y entretenimiento', priceMonthly: 7990 },
  { name: 'Apple TV+', slug: 'apple-tv-plus', category: 'Streaming', websiteUrl: 'https://tv.apple.com', description: 'Originales Apple', priceMonthly: 4990 },
  { name: 'Crunchyroll', slug: 'crunchyroll', category: 'Streaming', websiteUrl: 'https://www.crunchyroll.com', description: 'Anime', priceMonthly: 4990 },
  { name: 'Vix+', slug: 'vix-plus', category: 'Streaming', websiteUrl: 'https://vix.com', description: 'Contenido en español', priceMonthly: 3990 },
  { name: 'Pluto TV', slug: 'pluto-tv', category: 'Streaming', websiteUrl: 'https://pluto.tv', description: 'TV gratis con anuncios', priceMonthly: 0 },
  { name: 'Twitch Turbo', slug: 'twitch-turbo', category: 'Streaming', websiteUrl: 'https://www.twitch.tv', description: 'Sin anuncios en Twitch', priceMonthly: 5990 },

  // Productividad
  { name: 'Microsoft 365', slug: 'microsoft-365', category: 'Productividad', websiteUrl: 'https://www.microsoft.com/microsoft-365', description: 'Office + OneDrive', priceMonthly: 6990, priceYearly: 69900, priceFamily: 9990 },
  { name: 'Google One', slug: 'google-one', category: 'Productividad', websiteUrl: 'https://one.google.com', description: 'Almacenamiento Google', priceMonthly: 1990, priceYearly: 19900 },
  { name: 'Notion', slug: 'notion', category: 'Productividad', websiteUrl: 'https://www.notion.so', description: 'Notas y wikis', priceMonthly: 9990 },
  { name: 'Evernote', slug: 'evernote', category: 'Productividad', websiteUrl: 'https://evernote.com', description: 'Notas', priceMonthly: 7990 },
  { name: 'Todoist', slug: 'todoist', category: 'Productividad', websiteUrl: 'https://todoist.com', description: 'Gestión de tareas', priceMonthly: 4990 },
  { name: 'Slack', slug: 'slack', category: 'Productividad', websiteUrl: 'https://slack.com', description: 'Chat de equipos', priceMonthly: 7990 },
  { name: 'Zoom Pro', slug: 'zoom-pro', category: 'Productividad', websiteUrl: 'https://zoom.us', description: 'Videollamadas', priceMonthly: 14990 },
  { name: 'Dropbox', slug: 'dropbox', category: 'Productividad', websiteUrl: 'https://www.dropbox.com', description: 'Almacenamiento en la nube', priceMonthly: 9990 },
  { name: 'iCloud+', slug: 'icloud-plus', category: 'Productividad', websiteUrl: 'https://www.apple.com/icloud', description: 'Almacenamiento Apple', priceMonthly: 990 },
  { name: 'Canva Pro', slug: 'canva-pro', category: 'Diseño', websiteUrl: 'https://www.canva.com', description: 'Diseño gráfico', priceMonthly: 9990, priceYearly: 99900 },
  { name: 'Adobe Creative Cloud', slug: 'adobe-cc', category: 'Diseño', websiteUrl: 'https://www.adobe.com', description: 'Photoshop, Premiere, etc.', priceMonthly: 34990 },
  { name: 'Adobe Express', slug: 'adobe-express', category: 'Diseño', websiteUrl: 'https://www.adobe.com/express', description: 'Diseño rápido', priceMonthly: 9990 },
  { name: 'Figma', slug: 'figma', category: 'Diseño', websiteUrl: 'https://www.figma.com', description: 'UI/UX design', priceMonthly: 14990 },
  { name: 'ChatGPT Plus', slug: 'chatgpt-plus', category: 'IA', websiteUrl: 'https://chatgpt.com', description: 'GPT-4 y más', priceMonthly: 19990 },
  { name: 'Claude Pro', slug: 'claude-pro', category: 'IA', websiteUrl: 'https://claude.ai', description: 'Anthropic Claude', priceMonthly: 19990 },
  { name: 'GitHub Copilot', slug: 'github-copilot', category: 'IA', websiteUrl: 'https://github.com/features/copilot', description: 'IA para código', priceMonthly: 9990 },
  { name: 'Midjourney', slug: 'midjourney', category: 'IA', websiteUrl: 'https://www.midjourney.com', description: 'Imágenes con IA', priceMonthly: 9990 },
  { name: 'Cursor', slug: 'cursor', category: 'IA', websiteUrl: 'https://cursor.com', description: 'Editor con IA', priceMonthly: 19990 },
  { name: 'Perplexity Pro', slug: 'perplexity-pro', category: 'IA', websiteUrl: 'https://www.perplexity.ai', description: 'Búsqueda con IA', priceMonthly: 19990 },

  // Gaming
  { name: 'Xbox Game Pass', slug: 'xbox-game-pass', category: 'Gaming', websiteUrl: 'https://www.xbox.com/game-pass', description: 'Catálogo de juegos Xbox', priceMonthly: 9990 },
  { name: 'PlayStation Plus', slug: 'ps-plus', category: 'Gaming', websiteUrl: 'https://www.playstation.com/ps-plus', description: 'Online + juegos mensuales', priceMonthly: 7990, priceYearly: 49990 },
  { name: 'Nintendo Switch Online', slug: 'nintendo-online', category: 'Gaming', websiteUrl: 'https://www.nintendo.com', description: 'Online Switch', priceMonthly: 2990, priceYearly: 19990 },
  { name: 'EA Play', slug: 'ea-play', category: 'Gaming', websiteUrl: 'https://www.ea.com/ea-play', description: 'Juegos EA', priceMonthly: 4990 },
  { name: 'Steam', slug: 'steam', category: 'Gaming', websiteUrl: 'https://store.steampowered.com', description: 'Juegos PC (compras)', priceMonthly: null },
  { name: 'GeForce Now', slug: 'geforce-now', category: 'Gaming', websiteUrl: 'https://www.nvidia.com/geforce-now', description: 'Cloud gaming', priceMonthly: 9990 },

  // Fitness / Salud
  { name: 'Strava', slug: 'strava', category: 'Salud', websiteUrl: 'https://www.strava.com', description: 'Running y ciclismo', priceMonthly: 7990 },
  { name: 'MyFitnessPal', slug: 'myfitnesspal', category: 'Salud', websiteUrl: 'https://www.myfitnesspal.com', description: 'Calorías y nutrición', priceMonthly: 4990 },
  { name: 'Headspace', slug: 'headspace', category: 'Salud', websiteUrl: 'https://www.headspace.com', description: 'Meditación', priceMonthly: 9990 },
  { name: 'Calm', slug: 'calm', category: 'Salud', websiteUrl: 'https://www.calm.com', description: 'Sueño y meditación', priceMonthly: 9990 },
  { name: 'Peloton', slug: 'peloton', category: 'Salud', websiteUrl: 'https://www.onepeloton.com', description: 'Entrenamientos', priceMonthly: 12990 },

  // Noticias / Lectura
  { name: 'Kindle Unlimited', slug: 'kindle-unlimited', category: 'Lectura', websiteUrl: 'https://www.amazon.com/kindle-unlimited', description: 'Libros digitales', priceMonthly: 9990 },
  { name: 'Audible', slug: 'audible', category: 'Lectura', websiteUrl: 'https://www.audible.com', description: 'Audiolibros', priceMonthly: 14990 },
  { name: 'Medium', slug: 'medium', category: 'Lectura', websiteUrl: 'https://medium.com', description: 'Artículos', priceMonthly: 4990 },
  { name: 'The New York Times', slug: 'nytimes', category: 'Noticias', websiteUrl: 'https://www.nytimes.com', description: 'Noticias', priceMonthly: 4990 },
  { name: 'El Mercurio Digital', slug: 'el-mercurio', category: 'Noticias', websiteUrl: 'https://digital.elmercurio.com', description: 'Diario chileno', priceMonthly: 9990 },
  { name: 'La Tercera', slug: 'la-tercera', category: 'Noticias', websiteUrl: 'https://www.latercera.com', description: 'Noticias Chile', priceMonthly: 4990 },
  { name: 'Emol', slug: 'emol', category: 'Noticias', websiteUrl: 'https://www.emol.com', description: 'Noticias', priceMonthly: 3990 },

  // Telecom / Chile
  { name: 'Movistar Fibra', slug: 'movistar-fibra', category: 'Telecom', websiteUrl: 'https://www.movistar.cl', description: 'Internet hogar', priceMonthly: 24990 },
  { name: 'Entel Hogar', slug: 'entel-hogar', category: 'Telecom', websiteUrl: 'https://www.entel.cl', description: 'Internet / TV', priceMonthly: 22990 },
  { name: 'VTR', slug: 'vtr', category: 'Telecom', websiteUrl: 'https://www.vtr.com', description: 'Internet y cable', priceMonthly: 25990 },
  { name: 'WOM Plan', slug: 'wom-plan', category: 'Telecom', websiteUrl: 'https://www.wom.cl', description: 'Plan móvil', priceMonthly: 9990 },
  { name: 'Claro Plan', slug: 'claro-plan', category: 'Telecom', websiteUrl: 'https://www.clarochile.cl', description: 'Plan móvil', priceMonthly: 10990 },
  { name: 'Directv Go', slug: 'directv-go', category: 'Streaming', websiteUrl: 'https://www.directvgo.com', description: 'TV en vivo', priceMonthly: 9990 },
  { name: 'Zapping', slug: 'zapping', category: 'Streaming', websiteUrl: 'https://www.zapping.com', description: 'TV online Chile', priceMonthly: 7990 },

  // Finanzas
  { name: 'Bankingly / banca', slug: 'banca-online', category: 'Finanzas', websiteUrl: null, description: 'Comisiones / packs bancarios', priceMonthly: null },
  { name: 'Fintual', slug: 'fintual', category: 'Finanzas', websiteUrl: 'https://fintual.cl', description: 'Inversiones', priceMonthly: 0 },
  { name: 'Racional', slug: 'racional', category: 'Finanzas', websiteUrl: 'https://racional.cl', description: 'Inversiones', priceMonthly: 0 },
  { name: 'Tenpo', slug: 'tenpo', category: 'Finanzas', websiteUrl: 'https://www.tenpo.cl', description: 'Cuenta digital', priceMonthly: 0 },
  { name: 'MACH', slug: 'mach', category: 'Finanzas', websiteUrl: 'https://www.mach.cl', description: 'Billetera digital', priceMonthly: 0 },
  { name: 'Mercado Pago', slug: 'mercado-pago', category: 'Finanzas', websiteUrl: 'https://www.mercadopago.cl', description: 'Pagos y cuenta', priceMonthly: 0 },

  // Educación
  { name: 'Duolingo Super', slug: 'duolingo-super', category: 'Educación', websiteUrl: 'https://www.duolingo.com', description: 'Idiomas', priceMonthly: 7990 },
  { name: 'Coursera Plus', slug: 'coursera-plus', category: 'Educación', websiteUrl: 'https://www.coursera.org', description: 'Cursos online', priceMonthly: 39990 },
  { name: 'Udemy', slug: 'udemy', category: 'Educación', websiteUrl: 'https://www.udemy.com', description: 'Cursos (compras)', priceMonthly: null },
  { name: 'Domestika', slug: 'domestika', category: 'Educación', websiteUrl: 'https://www.domestika.org', description: 'Cursos creativos', priceMonthly: 9990 },
  { name: 'LinkedIn Premium', slug: 'linkedin-premium', category: 'Productividad', websiteUrl: 'https://www.linkedin.com/premium', description: 'Networking profesional', priceMonthly: 29990 },

  // Software / Dev
  { name: 'GitHub Pro', slug: 'github-pro', category: 'Desarrollo', websiteUrl: 'https://github.com', description: 'Repos avanzadas', priceMonthly: 3990 },
  { name: 'Vercel Pro', slug: 'vercel-pro', category: 'Desarrollo', websiteUrl: 'https://vercel.com', description: 'Hosting frontend', priceMonthly: 19990 },
  { name: 'Render', slug: 'render', category: 'Desarrollo', websiteUrl: 'https://render.com', description: 'Hosting backend', priceMonthly: 7000 },
  { name: 'Supabase Pro', slug: 'supabase-pro', category: 'Desarrollo', websiteUrl: 'https://supabase.com', description: 'Backend y DB', priceMonthly: 24990 },
  { name: 'DigitalOcean', slug: 'digitalocean', category: 'Desarrollo', websiteUrl: 'https://www.digitalocean.com', description: 'Cloud VPS', priceMonthly: 6000 },
  { name: 'AWS', slug: 'aws', category: 'Desarrollo', websiteUrl: 'https://aws.amazon.com', description: 'Cloud (variable)', priceMonthly: null },
  { name: 'JetBrains', slug: 'jetbrains', category: 'Desarrollo', websiteUrl: 'https://www.jetbrains.com', description: 'IDEs', priceMonthly: 19990 },
  { name: '1Password', slug: '1password', category: 'Seguridad', websiteUrl: 'https://1password.com', description: 'Gestor de contraseñas', priceMonthly: 3990 },
  { name: 'Bitwarden Premium', slug: 'bitwarden', category: 'Seguridad', websiteUrl: 'https://bitwarden.com', description: 'Contraseñas', priceMonthly: 990 },
  { name: 'NordVPN', slug: 'nordvpn', category: 'Seguridad', websiteUrl: 'https://nordvpn.com', description: 'VPN', priceMonthly: 7990, priceYearly: 39990 },
  { name: 'ExpressVPN', slug: 'expressvpn', category: 'Seguridad', websiteUrl: 'https://www.expressvpn.com', description: 'VPN', priceMonthly: 9990 },
  { name: 'Norton 360', slug: 'norton-360', category: 'Seguridad', websiteUrl: 'https://cl.norton.com', description: 'Antivirus', priceMonthly: 4990 },

  // Delivery / Lifestyle Chile
  { name: 'Uber One', slug: 'uber-one', category: 'Delivery', websiteUrl: 'https://www.uber.com', description: 'Envíos y viajes', priceMonthly: 4990 },
  { name: 'Rappi Prime', slug: 'rappi-prime', category: 'Delivery', websiteUrl: 'https://www.rappi.cl', description: 'Delivery sin costo de envío', priceMonthly: 4990 },
  { name: 'PedidosYa Plus', slug: 'pedidosya-plus', category: 'Delivery', websiteUrl: 'https://www.pedidosya.cl', description: 'Delivery', priceMonthly: 3990 },
  { name: 'Cornershop by Uber', slug: 'cornershop', category: 'Delivery', websiteUrl: 'https://cornershopapp.com', description: 'Supermercado', priceMonthly: null },
  { name: 'Falabella CMR', slug: 'falabella-cmr', category: 'Retail', websiteUrl: 'https://www.falabella.com', description: 'Membresía / tarjetas', priceMonthly: null },
  { name: 'Paris', slug: 'paris', category: 'Retail', websiteUrl: 'https://www.paris.cl', description: 'Retail', priceMonthly: null },
  { name: 'Ripley', slug: 'ripley', category: 'Retail', websiteUrl: 'https://www.ripley.cl', description: 'Retail', priceMonthly: null },

  // Más streaming / música
  { name: 'Deezer', slug: 'deezer', category: 'Música', websiteUrl: 'https://www.deezer.com', description: 'Música', priceMonthly: 4990, priceFamily: 7990 },
  { name: 'Tidal', slug: 'tidal', category: 'Música', websiteUrl: 'https://tidal.com', description: 'HiFi', priceMonthly: 9990 },
  { name: 'SoundCloud Go', slug: 'soundcloud-go', category: 'Música', websiteUrl: 'https://soundcloud.com', description: 'Música indie', priceMonthly: 4990 },
  { name: 'Podcasts Apple', slug: 'apple-podcasts', category: 'Música', websiteUrl: 'https://podcasts.apple.com', description: 'Suscripciones podcast', priceMonthly: null },
  { name: 'Mubi', slug: 'mubi', category: 'Streaming', websiteUrl: 'https://mubi.com', description: 'Cine de autor', priceMonthly: 6990 },
  { name: 'Criterion Channel', slug: 'criterion', category: 'Streaming', websiteUrl: 'https://www.criterionchannel.com', description: 'Cine clásico', priceMonthly: 9990 },

  // Misc
  { name: 'Patreon', slug: 'patreon', category: 'Otros', websiteUrl: 'https://www.patreon.com', description: 'Creadores', priceMonthly: null },
  { name: 'OnlyFans', slug: 'onlyfans', category: 'Otros', websiteUrl: 'https://onlyfans.com', description: 'Contenido', priceMonthly: null },
  { name: 'Discord Nitro', slug: 'discord-nitro', category: 'Otros', websiteUrl: 'https://discord.com', description: 'Boost y emotes', priceMonthly: 4990 },
  { name: 'Telegram Premium', slug: 'telegram-premium', category: 'Otros', websiteUrl: 'https://telegram.org', description: 'Chat premium', priceMonthly: 3990 },
  { name: 'WhatsApp Business', slug: 'whatsapp-business', category: 'Otros', websiteUrl: 'https://business.whatsapp.com', description: 'API / herramientas', priceMonthly: null },
  { name: 'Grammarly Premium', slug: 'grammarly', category: 'Productividad', websiteUrl: 'https://www.grammarly.com', description: 'Escritura en inglés', priceMonthly: 11990 },
  { name: 'LastPass', slug: 'lastpass', category: 'Seguridad', websiteUrl: 'https://www.lastpass.com', description: 'Contraseñas', priceMonthly: 2990 },
  { name: 'Surfshark', slug: 'surfshark', category: 'Seguridad', websiteUrl: 'https://surfshark.com', description: 'VPN', priceMonthly: 4990 },
  { name: 'Dashlane', slug: 'dashlane', category: 'Seguridad', websiteUrl: 'https://www.dashlane.com', description: 'Contraseñas', priceMonthly: 4990 },
  { name: 'Trello Premium', slug: 'trello', category: 'Productividad', websiteUrl: 'https://trello.com', description: 'Tableros', priceMonthly: 5990 },
  { name: 'Asana', slug: 'asana', category: 'Productividad', websiteUrl: 'https://asana.com', description: 'Proyectos', priceMonthly: 10990 },
  { name: 'Monday.com', slug: 'monday', category: 'Productividad', websiteUrl: 'https://monday.com', description: 'Work OS', priceMonthly: 8990 },
  { name: 'ClickUp', slug: 'clickup', category: 'Productividad', websiteUrl: 'https://clickup.com', description: 'Productividad', priceMonthly: 5990 },
  { name: 'Linear', slug: 'linear', category: 'Desarrollo', websiteUrl: 'https://linear.app', description: 'Issues', priceMonthly: 8000 },
  { name: 'Notion AI', slug: 'notion-ai', category: 'IA', websiteUrl: 'https://www.notion.so/product/ai', description: 'IA en Notion', priceMonthly: 9990 },
  { name: 'Grammarly GO', slug: 'grammarly-go', category: 'IA', websiteUrl: 'https://www.grammarly.com', description: 'IA escritura', priceMonthly: 11990 },
  { name: 'Runway', slug: 'runway', category: 'IA', websiteUrl: 'https://runwayml.com', description: 'Video IA', priceMonthly: 14990 },
  { name: 'ElevenLabs', slug: 'elevenlabs', category: 'IA', websiteUrl: 'https://elevenlabs.io', description: 'Voz IA', priceMonthly: 4990 },
  { name: 'CapCut Pro', slug: 'capcut-pro', category: 'Diseño', websiteUrl: 'https://www.capcut.com', description: 'Edición de video', priceMonthly: 7990 },
  { name: 'Envato Elements', slug: 'envato', category: 'Diseño', websiteUrl: 'https://elements.envato.com', description: 'Assets creativos', priceMonthly: 16990 },
  { name: 'Unsplash+', slug: 'unsplash-plus', category: 'Diseño', websiteUrl: 'https://unsplash.com/plus', description: 'Fotos premium', priceMonthly: 9990 },
  { name: 'Shutterstock', slug: 'shutterstock', category: 'Diseño', websiteUrl: 'https://www.shutterstock.com', description: 'Stock photos', priceMonthly: 24990 },
  { name: 'Behance Pro', slug: 'behance', category: 'Diseño', websiteUrl: 'https://www.behance.net', description: 'Portafolio', priceMonthly: 4990 },
  { name: 'Dribbble Pro', slug: 'dribbble', category: 'Diseño', websiteUrl: 'https://dribbble.com', description: 'Diseño community', priceMonthly: 5990 },
  { name: 'Skillshare', slug: 'skillshare', category: 'Educación', websiteUrl: 'https://www.skillshare.com', description: 'Cursos creativos', priceMonthly: 9990 },
  { name: 'MasterClass', slug: 'masterclass', category: 'Educación', websiteUrl: 'https://www.masterclass.com', description: 'Clases de expertos', priceMonthly: 14990 },
  { name: 'Brilliant', slug: 'brilliant', category: 'Educación', websiteUrl: 'https://brilliant.org', description: 'STEM interactivo', priceMonthly: 14990 },
  { name: 'Babbel', slug: 'babbel', category: 'Educación', websiteUrl: 'https://www.babbel.com', description: 'Idiomas', priceMonthly: 7990 },
  { name: 'Busuu', slug: 'busuu', category: 'Educación', websiteUrl: 'https://www.busuu.com', description: 'Idiomas', priceMonthly: 6990 },
  { name: 'Preply', slug: 'preply', category: 'Educación', websiteUrl: 'https://preply.com', description: 'Clases particulares', priceMonthly: null },
  { name: 'Italki', slug: 'italki', category: 'Educación', websiteUrl: 'https://www.italki.com', description: 'Idiomas con tutores', priceMonthly: null },
  { name: 'Wix Premium', slug: 'wix', category: 'Desarrollo', websiteUrl: 'https://www.wix.com', description: 'Sitios web', priceMonthly: 12990 },
  { name: 'Squarespace', slug: 'squarespace', category: 'Desarrollo', websiteUrl: 'https://www.squarespace.com', description: 'Sitios web', priceMonthly: 15990 },
  { name: 'WordPress.com', slug: 'wordpress', category: 'Desarrollo', websiteUrl: 'https://wordpress.com', description: 'Blogs y sitios', priceMonthly: 4990 },
  { name: 'Shopify', slug: 'shopify', category: 'Retail', websiteUrl: 'https://www.shopify.com', description: 'E-commerce', priceMonthly: 29990 },
  { name: 'Mailchimp', slug: 'mailchimp', category: 'Productividad', websiteUrl: 'https://mailchimp.com', description: 'Email marketing', priceMonthly: 9990 },
  { name: 'ConvertKit', slug: 'convertkit', category: 'Productividad', websiteUrl: 'https://convertkit.com', description: 'Email creators', priceMonthly: 14990 },
  { name: 'Substack', slug: 'substack', category: 'Lectura', websiteUrl: 'https://substack.com', description: 'Newsletters', priceMonthly: null },
  { name: 'BeReal', slug: 'bereal', category: 'Otros', websiteUrl: 'https://bere.al', description: 'Red social', priceMonthly: 0 },
  { name: 'X Premium', slug: 'x-premium', category: 'Otros', websiteUrl: 'https://x.com', description: 'Twitter Blue', priceMonthly: 8990 },
  { name: 'Meta Verified', slug: 'meta-verified', category: 'Otros', websiteUrl: 'https://www.meta.com', description: 'Instagram / Facebook', priceMonthly: 7990 },
  { name: 'Snapchat+', slug: 'snapchat-plus', category: 'Otros', websiteUrl: 'https://www.snapchat.com', description: 'Snapchat premium', priceMonthly: 3990 },
  { name: 'Pinterest Premium', slug: 'pinterest', category: 'Otros', websiteUrl: 'https://www.pinterest.com', description: 'Ideas y pins', priceMonthly: null },
  { name: 'Xbox Live Gold', slug: 'xbox-live-gold', category: 'Gaming', websiteUrl: 'https://www.xbox.com', description: 'Multiplayer (legacy)', priceMonthly: 6990 },
  { name: 'Humble Choice', slug: 'humble-choice', category: 'Gaming', websiteUrl: 'https://www.humblebundle.com', description: 'Juegos mensuales', priceMonthly: 11990 },
  { name: 'Ubisoft+', slug: 'ubisoft-plus', category: 'Gaming', websiteUrl: 'https://plus.ubisoft.com', description: 'Catálogo Ubisoft', priceMonthly: 14990 },
  { name: 'Apple Arcade', slug: 'apple-arcade', category: 'Gaming', websiteUrl: 'https://www.apple.com/apple-arcade', description: 'Juegos móviles', priceMonthly: 4990 },
  { name: 'Google Play Pass', slug: 'play-pass', category: 'Gaming', websiteUrl: 'https://play.google.com/about/pass', description: 'Juegos Android', priceMonthly: 2990 },
  { name: 'Fitbit Premium', slug: 'fitbit-premium', category: 'Salud', websiteUrl: 'https://www.fitbit.com', description: 'Wearables', priceMonthly: 7990 },
  { name: 'Whoop', slug: 'whoop', category: 'Salud', websiteUrl: 'https://www.whoop.com', description: 'Recovery y strain', priceMonthly: 29990 },
  { name: 'Noom', slug: 'noom', category: 'Salud', websiteUrl: 'https://www.noom.com', description: 'Pérdida de peso', priceMonthly: 39990 },
  { name: 'BetterHelp', slug: 'betterhelp', category: 'Salud', websiteUrl: 'https://www.betterhelp.com', description: 'Terapia online', priceMonthly: 199990 },
  { name: 'Oura Membership', slug: 'oura', category: 'Salud', websiteUrl: 'https://ouraring.com', description: 'Anillo de sueño', priceMonthly: 5990 },
  { name: 'Scribd', slug: 'scribd', category: 'Lectura', websiteUrl: 'https://www.scribd.com', description: 'Libros y docs', priceMonthly: 9990 },
  { name: 'Blinkist', slug: 'blinkist', category: 'Lectura', websiteUrl: 'https://www.blinkist.com', description: 'Resúmenes de libros', priceMonthly: 9990 },
  { name: 'Goodreads', slug: 'goodreads', category: 'Lectura', websiteUrl: 'https://www.goodreads.com', description: 'Libros (Amazon)', priceMonthly: 0 },
  { name: 'Le Monde', slug: 'le-monde', category: 'Noticias', websiteUrl: 'https://www.lemonde.fr', description: 'Noticias FR', priceMonthly: 9990 },
  { name: 'Washington Post', slug: 'washington-post', category: 'Noticias', websiteUrl: 'https://www.washingtonpost.com', description: 'Noticias', priceMonthly: 4990 },
  { name: 'Bloomberg', slug: 'bloomberg', category: 'Noticias', websiteUrl: 'https://www.bloomberg.com', description: 'Finanzas', priceMonthly: 34990 },
  { name: 'The Economist', slug: 'the-economist', category: 'Noticias', websiteUrl: 'https://www.economist.com', description: 'Análisis global', priceMonthly: 19990 },
  { name: 'Cencosud Scotiabank', slug: 'cencosud-scotia', category: 'Finanzas', websiteUrl: 'https://www.cencosud.cl', description: 'Tarjeta / puntos', priceMonthly: null },
  { name: 'Banco Estado', slug: 'banco-estado', category: 'Finanzas', websiteUrl: 'https://www.bancoestado.cl', description: 'Cuenta RUT / planes', priceMonthly: null },
  { name: 'Banco de Chile', slug: 'banco-chile', category: 'Finanzas', websiteUrl: 'https://www.bancochile.cl', description: 'Planes cuenta', priceMonthly: null },
  { name: 'BCI', slug: 'bci', category: 'Finanzas', websiteUrl: 'https://www.bci.cl', description: 'Banca', priceMonthly: null },
  { name: 'Santander Chile', slug: 'santander-cl', category: 'Finanzas', websiteUrl: 'https://www.santander.cl', description: 'Banca', priceMonthly: null },
  { name: 'Copec Pay', slug: 'copec-pay', category: 'Finanzas', websiteUrl: 'https://www.copec.cl', description: 'App combustible', priceMonthly: 0 },
  { name: 'Shell ClubSmart', slug: 'shell-club', category: 'Otros', websiteUrl: 'https://www.shell.cl', description: 'Puntos combustible', priceMonthly: 0 },
  { name: 'HBO Max (legacy)', slug: 'hbo-max-legacy', category: 'Streaming', websiteUrl: 'https://www.max.com', description: 'Alias Max', priceMonthly: 7990 },
  { name: 'Starzplay', slug: 'starzplay', category: 'Streaming', websiteUrl: 'https://www.starz.com', description: 'Series', priceMonthly: 4990 },
  { name: 'Acorn TV', slug: 'acorn-tv', category: 'Streaming', websiteUrl: 'https://acorn.tv', description: 'Británico', priceMonthly: 5990 },
  { name: 'BritBox', slug: 'britbox', category: 'Streaming', websiteUrl: 'https://www.britbox.com', description: 'BBC/ITV', priceMonthly: 6990 },
  { name: 'Curiosity Stream', slug: 'curiosity-stream', category: 'Streaming', websiteUrl: 'https://curiositystream.com', description: 'Documentales', priceMonthly: 3990 },
  { name: 'Nebula', slug: 'nebula', category: 'Streaming', websiteUrl: 'https://nebula.tv', description: 'Creadores', priceMonthly: 5990 },
  { name: 'Plex Pass', slug: 'plex-pass', category: 'Streaming', websiteUrl: 'https://www.plex.tv', description: 'Media server', priceMonthly: 4990, priceYearly: 39990 },
  { name: 'Emby Premiere', slug: 'emby', category: 'Streaming', websiteUrl: 'https://emby.media', description: 'Media server', priceMonthly: 4990 },
  { name: 'Jellyfin', slug: 'jellyfin', category: 'Streaming', websiteUrl: 'https://jellyfin.org', description: 'Media server gratis', priceMonthly: 0 },
  { name: 'Otra (personalizada)', slug: 'otra-personalizada', category: 'Otros', websiteUrl: null, description: 'Suscripción no listada', priceMonthly: null },
];
